// ═══════════════════════════════════════════════════════
// STORY DATA — Estados, Personajes y Narrativa
// ═══════════════════════════════════════════════════════

const STATES = [
  {name:'Ciudad de México', code:'CDMX', bonus:'fiscal_aggressive', note:'Fiscalía muy activa. Jueces experimentados.'},
  {name:'Nuevo León', code:'NL', bonus:'fiscal_tech', note:'Evidencia digital frecuente. Fiscalía técnica.'},
  {name:'Jalisco', code:'JAL', bonus:'police_pressure', note:'Policía usa técnicas de presión más intensas.'},
  {name:'Veracruz', code:'VER', bonus:'slow_process', note:'Proceso más lento. Más tiempo en prisión preventiva.'},
  {name:'Guerrero', code:'GRO', bonus:'corruption_risk', note:'Alta variabilidad en resoluciones judiciales.'},
  {name:'Estado de México', code:'EDOMEX', bonus:'overcrowded', note:'Centros de reclusión sobresaturados.'},
  {name:'Tamaulipas', code:'TAM', bonus:'organized_crime', note:'Fiscal relaciona todo con crimen organizado.'},
  {name:'Baja California', code:'BC', bonus:'border_laws', note:'Leyes de frontera más estrictas.'},
  {name:'Chihuahua', code:'CHI', bonus:'pioneer_accusatory', note:'Pionero en sistema acusatorio. Jueces preparados.'},
  {name:'Oaxaca', code:'OAX', bonus:'slow_process', note:'Procesos largos. Defensa pública limitada.'},
  {name:'Sinaloa', code:'SIN', bonus:'organized_crime', note:'Fuerte presencia de crimen organizado complica casos.'},
  {name:'Puebla', code:'PUE', bonus:'police_pressure', note:'Policía local con frecuente abuso de autoridad.'},
];

const CHARS = {
  ratero: {
    name: 'El Ratero', fullName: 'Héctor "El Cuate" Mendoza',
    crime: 'Robo con violencia (Art. 381 CPDF)', sprite:'ratero',
    startCalm:55, startPressure:35, startCred:50, startRisk:45,
    bgColor:'#1a0a00', bgEmoji:'🔪',
    intro: 'Ayer en la noche, amagaste a un comerciante en la Col. Guerrero. Alguien te vio y llamó al 911. La patrulla te alcanzó 3 cuadras después.'
  },
  narco: {
    name: 'El Distribuidor', fullName: 'Rafael "El Rafa" Orozco',
    crime: 'Contra la Salud — Narcomenudeo (LGS Art. 475)', sprite:'narco',
    startCalm:65, startPressure:25, startCred:40, startRisk:60,
    bgColor:'#001a00', bgEmoji:'💊',
    intro: 'Eras punto de distribución en tu colonia. Te tendieron una trampa: un comprador era informante. Te detuvieron con 120g de cristal y $4,200 pesos.'
  },
  loco: {
    name: 'El Inimputable', fullName: 'Genaro (sin apellido conocido)',
    crime: 'Daño en propiedad / Lesiones / Amenazas', sprite:'loco',
    startCalm:30, startPressure:50, startCred:30, startRisk:25,
    bgColor:'#0a001a', bgEmoji:'🪨',
    intro: 'Llevas semanas durmiendo bajo el puente de Insurgentes. Esta tarde aventaste piedras a los carros y golpeaste a un señor en la cabeza. Alguien filmó todo.'
  }
};

const STORY = {

ratero: [
  // FASE 1: DETENCIÓN
  {phase:1, location:'Calle — 23:14h', bg:'street_night', left:'cop', right:'ratero',
   leftName:'AGENTE RAMÍREZ', leftRole:'Policía Preventiva',
   speaker:'cop',
   text:'¡ALTO! ¡Manos donde las vea! ¿Sabes por qué te detuvimos, amigo?',
   options:[
     {text:'NEGAR TODO — "Yo no fui, oficial, me confundió"', changes:{calm:-5,cred:-10,risk:+5}, flag:'denied', next:1,
      consequence:'El oficial frunce el ceño. Alguien te identificó en video.'},
     {text:'GUARDAR SILENCIO — No dices nada', changes:{calm:+5,pressure:-5,cred:+5,risk:-5}, flag:'silent', next:1,
      consequence:'Correcto. El Art. 128 CNPP garantiza tu derecho a no declarar.'},
     {text:'INVENTAR MENTIRA — "Venía del trabajo, oficial"', changes:{calm:-10,cred:-15,risk:+10}, flag:'lied', next:1,
      consequence:'La mentira queda registrada. Si la retractas después, daña tu credibilidad.'},
     {text:'PONERTE AGRESIVO — "¡Suélteme! ¡Abuso!"', changes:{calm:-20,pressure:+15,risk:+15}, flag:'aggressive', next:1,
      consequence:'El oficial llama refuerzos. Tu actitud quedará en el reporte.'},
   ]},
  {phase:1, location:'Patrulla — Camino a la delegación', bg:'patrol_car', left:'cop_angry', right:'ratero',
   leftName:'AGENTE RAMÍREZ', leftRole:'Policía Preventiva',
   speaker:'cop',
   text:'Hay un video donde se ve claramente a alguien con tu ropa. Mejor me ayudas. ¿Tienes cómplices?',
   options:[
     {text:'MENCIONAR A ALGUIEN — Inventas un cómplice', changes:{cred:-20,risk:+10}, flag:'snitched', next:2,
      consequence:'Acabas de involucrarte más. Si es falso, es una denuncia falsa.'},
     {text:'PEDIR ABOGADO — "No declaro sin abogado"', changes:{calm:+10,cred:+10,risk:-10}, flag:'asked_lawyer', next:2,
      consequence:'¡Correcto! Art. 128 Fr. VIII CNPP. El policía está obligado a respetar esto.'},
     {text:'CALLARTE — Solo miras por la ventana', changes:{calm:+5,pressure:+5}, flag:'silent2', next:2,
      consequence:'Silencio estratégico. No es lo mismo que negar.'},
     {text:'LLORAR Y ROGAR — "Oficial, tengo familia"', changes:{calm:-5,pressure:+10,cred:-5}, flag:'cried', next:2,
      consequence:'El agente anota: "imputado emocionalmente inestable".'},
   ]},
  {phase:1, location:'CEDE — Sala de espera', bg:'station', left:'cop', right:'ratero',
   leftName:'CABO TORRES', leftRole:'Turno de custodia',
   speaker:'cop',
   text:'Te van a pasar a declarar ante el Ministerio Público. Tienes derecho a un abogado. ¿Tienes dinero para uno particular?',
   options:[
     {text:'SÍ — Llamaré a un abogado particular', changes:{cred:+5,risk:-5}, flag:'private_lawyer', next:3,
      consequence:'Tienes 30 minutos para localizarlo. Si no llega, te asignan defensor público.'},
     {text:'NO — Quiero un Defensor Público', changes:{calm:+5}, flag:'public_lawyer', next:3,
      consequence:'El defensor público tiene 150 casos simultáneos. Hará lo que pueda.'},
     {text:'NADA — No quiero abogado', changes:{cred:-10,risk:+20}, flag:'no_lawyer', next:3,
      consequence:'ERROR CRÍTICO. Sin abogado vas desprotegido. El CNPP te protege pero no puedes invocarlo solo.'},
   ]},

  // FASE 2: INTERROGATORIO
  {phase:2, location:'Ministerio Público — Cubículo 3', bg:'interrogation', left:'fiscal', right:'ratero',
   leftName:'MP CASTELLANOS', leftRole:'Ministerio Público',
   speaker:'fiscal',
   text:'Señor Mendoza, se le imputa robo calificado. El Art. 220 del CNPP me permite tomarte declaración. ¿En qué estaba usted a las 11pm?',
   options:[
     {text:'MENTIR — "Estaba en casa de un amigo"', changes:{cred:-10,risk:+10}, flag:'lied_mp', next:4,
      consequence:'El MP anota. Verificarán la coartada. Si falla: agrava tu situación.'},
     {text:'VERDAD PARCIAL — "Andaba en la zona pero no fui yo"', changes:{calm:-5,cred:+5,risk:-5}, flag:'partial_truth', next:4,
      consequence:'Táctica mixta. Mantiene algo de credibilidad pero te sitúa en la escena.'},
     {text:'SILENCIO — Ejerces tu derecho', changes:{calm:+10,cred:+10,risk:-10}, flag:'silent_mp', next:4,
      consequence:'Perfecto. El silencio NO es prueba de culpabilidad (Art. 20 CPEUM).'},
     {text:'ATACAR AL MP — "Esta detención fue ilegal"', changes:{calm:-10,pressure:+15,cred:-5,risk:-5}, flag:'attacked_mp', next:4,
      consequence:'Si la detención fue ilegal, esto puede ser tu salvación. Pero necesitas probarlo.'},
   ]},
  {phase:2, location:'Ministerio Público — Sala de videoconferencia', bg:'interrogation', left:'fiscal', right:'ratero',
   leftName:'MP CASTELLANOS', leftRole:'Ministerio Público',
   speaker:'fiscal',
   text:'Tenemos el video. Se ve claramente a alguien con una chamarra IGUAL a la tuya. ¿Cómo explica eso?',
   options:[
     {text:'CONTRADECIR — "Hay millones de chamarras iguales"', changes:{calm:-5,cred:+5}, flag:'contradict', next:5,
      consequence:'Válido. La similitud no es identidad. El MP necesita más que eso.'},
     {text:'CEDER — "...sí, soy yo, pero fue sin querer"', changes:{cred:-20,risk:+25}, flag:'confessed', next:5,
      consequence:'GRAVE. Acabas de confesar. Esto cambiará el proceso completamente.'},
     {text:'PEDIR VER EL VIDEO — "Quiero ver esa supuesta evidencia"', changes:{calm:+5,cred:+5,risk:-5}, flag:'demand_evidence', next:5,
      consequence:'Correcto. El Art. 337 CNPP te da derecho a conocer las pruebas en tu contra.'},
     {text:'MENTIR MÁS — "Yo estaba en Tepito, no en Guerrero"', changes:{cred:-15,risk:+5}, flag:'lied2', next:5,
      consequence:'Otra mentira que verificar. Cada mentira es una trampa potencial.'},
   ]},

  // FASE 3: FISCALÍA — AUDIENCIA INICIAL
  {phase:3, location:'Sala de Audiencias — Audiencia Inicial', bg:'court', left:'fiscal', right:'ratero',
   leftName:'AGENTE DEL MP', leftRole:'Fiscalía del Estado',
   speaker:'fiscal',
   text:'Señoría, solicitamos PRISIÓN PREVENTIVA JUSTIFICADA. El imputado representa riesgo de fuga. Hay video, hay víctima, hay chamarra como la del video.',
   options:[
     {text:'DEJAR QUE EL ABOGADO HABLE — "Que hable mi defensa"', changes:{calm:+10,cred:+5,risk:-5}, flag:'lawyer_speaks', next:6,
      consequence:'Correcto. Esta es la función del abogado defensor.'},
     {text:'INTERRUMPIR — "¡Eso es mentira, señor juez!"', changes:{calm:-15,pressure:+15,cred:-15,risk:+5}, flag:'outburst', next:6,
      consequence:'El juez te llama al orden. Las interrupciones dañan tu caso.'},
     {text:'NEGAR SERENAMENTE — Mueves la cabeza con calma', changes:{calm:+5,cred:+5}, flag:'calm_denial', next:6,
      consequence:'El lenguaje corporal importa. El juez lo nota.'},
   ]},

  // FASE 4: DEFENSOR
  {phase:4, location:'Sala de Espera — Previo a audiencia', bg:'defender', left:'abogado', right:'ratero',
   leftName:'LIC. DOMÍNGUEZ', leftRole:'Defensor Público',
   speaker:'abogado',
   text:'Mire, el video no es tan claro. Voy a argumentar que la identificación fue sugestiva. PERO... necesito que no hable más de lo necesario. ¿Me entiende?',
   options:[
     {text:'SEGUIR SU CONSEJO — "Sí, licenciado, usted manda"', changes:{calm:+10,cred:+10,risk:-15}, flag:'follow_lawyer', next:7,
      consequence:'Excelente. La confianza en tu defensor es fundamental.'},
     {text:'IGNORARLO — "Yo sé lo que hago"', changes:{calm:-10,cred:-10,risk:+10}, flag:'ignore_lawyer', next:7,
      consequence:'Tu ego puede costarte. El licenciado conoce el proceso mejor que tú.'},
     {text:'PONERTE AGRESIVO — "¿Pa qué sirve usted si no me va a sacar?"', changes:{calm:-20,pressure:+20,cred:-5,risk:+5}, flag:'attack_lawyer', next:7,
      consequence:'El defensor público puede solicitar que te asignen otro. El proceso se complica.'},
     {text:'CUESTIONAR SU ESTRATEGIA — "¿Y si el video sí muestra mi cara?"', changes:{calm:-5,cred:+5}, flag:'question_lawyer', next:7,
      consequence:'Pregunta válida. Identificas una falla en la estrategia del defensor.'},
   ]},
  {phase:4, location:'Sala de Audiencias', bg:'court', left:'abogado', right:'ratero',
   leftName:'LIC. DOMÍNGUEZ', leftRole:'Defensor Público',
   speaker:'abogado',
   text:'El MP dice que el video lo muestra claramente. Yo digo que la calidad es deficiente. Señoría, solicito se haga análisis pericial del video. ¿Qué dice usted, señor Mendoza?',
   options:[
     {text:'APOYAR AL ABOGADO — "Sí, el video no es claro, señoría"', changes:{cred:+10,risk:-10}, flag:'support_lawyer', next:8,
      consequence:'Alineado con tu defensa. Presentas un frente unificado.'},
     {text:'CONTRADECIR SIN QUERER — "...bueno, era de noche y yo..."', changes:{cred:-15,risk:+15}, flag:'contradict_lawyer', next:8,
      consequence:'ERROR. Acabas de darle munición al fiscal.'},
   ]},

  // FASE 5: JUEZ
  {phase:5, location:'Sala de Audiencias — Audiencia de Vinculación', bg:'judge', left:'juez', right:'ratero',
   leftName:'JUEZ DE CONTROL', leftRole:'Poder Judicial — CNPP',
   speaker:'juez',
   text:'Voy a tomar en cuenta todo lo actuado. El imputado tiene derecho a la última palabra antes de que dicte mi resolución. ¿Algo que decir?',
   options:[
     {text:'PEDIR PERDÓN — "Me arrepiento, señor juez"', changes:{cred:+5,risk:-5}, flag:'apologize', next:'end'},
     {text:'DECLARARTE INOCENTE — "Soy inocente y voy a demostrarlo"', changes:{calm:+5,cred:+5,risk:-5}, flag:'innocent', next:'end'},
     {text:'QUEDARTE CALLADO — Solo inclinas la cabeza', changes:{calm:+5}, flag:'silent_judge', next:'end'},
     {text:'ATACAR AL SISTEMA — "Este juicio es una farsa"', changes:{calm:-20,cred:-20,risk:+15}, flag:'attack_system', next:'end'},
   ]},
],

narco: [
  {phase:1, location:'Estacionamiento del Oxxo — 21:30h', bg:'street_night', left:'cop_angry', right:'narco',
   leftName:'AGENTE FLORES', leftRole:'Policía Ministerial',
   speaker:'cop',
   text:'¡Operativo! ¡Al suelo! ¡Manos en la nuca! Encontramos sustancias en tu mochila. ¿De quién son?',
   options:[
     {text:'NEGAR — "No son mías, alguien me las dejó"', changes:{calm:-10,cred:-15,risk:+10}, flag:'denied', next:1,
      consequence:'Clásica defensa. Difícil de sostener si tu ADN está en las bolsas.'},
     {text:'SILENCIO TOTAL — No dices una palabra', changes:{calm:+10,cred:+10,risk:-10}, flag:'silent', next:1,
      consequence:'Excelente. El silencio protege. No puedes autoincriminarte.'},
     {text:'INVENTAR — "Las iba a entregar a alguien... no sé a quién"', changes:{cred:-20,risk:+15}, flag:'lied', next:1,
      consequence:'Eso suena peor que nada. Implica conocimiento del ilícito.'},
     {text:'NEGOCIAR — "¿Cuánto necesita, oficial?"', changes:{calm:-20,pressure:+30,risk:+30}, flag:'bribe', next:1,
      consequence:'GRAVE ERROR. Intento de soborno. Art. 222 CP Federal. Esto se suma a tu caso.'},
   ]},
  {phase:1, location:'Agencia del Ministerio Público', bg:'station', left:'fiscal', right:'narco',
   leftName:'AGENTE MP GUERRA', leftRole:'Ministerio Público Federal',
   speaker:'fiscal',
   text:'120 gramos de metanfetamina. Eso es narcomenudeo, Art. 475 Ley General de Salud. Penas de 4 a 8 años. A menos que... cooperes.',
   options:[
     {text:'PREGUNTAR QUÉ SIGNIFICA COOPERAR', changes:{calm:-5,pressure:+10}, flag:'ask_cooperate', next:2,
      consequence:'El MP quiere nombres. Si das información, puede haber criterio de oportunidad.'},
     {text:'RECHAZAR COOPERAR — "No tengo nada que decir"', changes:{calm:+5,cred:+10,risk:-5}, flag:'refuse_cooperate', next:2,
      consequence:'Silencio estratégico. No te conviertes en testigo contra nadie.'},
     {text:'EXIGIR VER TU ABOGADO — "¡No hablo sin mi abogado!"', changes:{calm:+10,cred:+15,risk:-10}, flag:'demand_lawyer', next:2,
      consequence:'CORRECTO. Esta es exactamente la respuesta que debías dar.'},
   ]},
  {phase:2, location:'Cubículo de interrogatorio', bg:'interrogation', left:'fiscal', right:'narco',
   leftName:'MP GUERRA', leftRole:'Agente del Ministerio Público',
   speaker:'fiscal',
   text:'El informante dice que llevas 8 meses operando en tu colonia. Tenemos fotos, fechas, montos. ¿Trabajas para alguien o eres independiente?',
   options:[
     {text:'MENTIR — "Solo lo hice una vez, soy consumidor"', changes:{cred:-15,risk:+5}, flag:'lied_mp', next:3,
      consequence:'120g está muy por encima del límite de consumo personal. No te lo creerán.'},
     {text:'SILENCIO — No respondes', changes:{calm:+10,cred:+10,risk:-5}, flag:'silent_mp', next:3,
      consequence:'El MP intenta provocarte. No caigas.'},
     {text:'ATACAR LA PRUEBA — "¿Quién es ese informante? ¡Quiero confrontarlo!"', changes:{calm:-5,cred:+10,risk:-10}, flag:'attack_evidence', next:3,
      consequence:'Derecho de confrontación (Art. 20 CPEUM). Si el informante no comparece, esa prueba se debilita.'},
     {text:'REVELAR AL JEFE — Mencionas un nombre', changes:{calm:-10,cred:-10,risk:+20,pressure:+20}, flag:'snitch', next:3,
      consequence:'Has delatado. Puede reducir tu pena... o ponerte en peligro.'},
   ]},
  {phase:3, location:'Audiencia Inicial — Sala B', bg:'court', left:'fiscal', right:'narco',
   leftName:'FISCAL ESPECIALIZADO', leftRole:'Fiscalía Especializada en Narcomenudeo',
   speaker:'fiscal',
   text:'Señoría, por el peso de la sustancia, el historial del imputado y el riesgo de obstrucción, solicitamos PRISIÓN PREVENTIVA. Además, iniciaremos proceso de extinción de dominio de su vehículo.',
   options:[
     {text:'DEJAR HABLAR AL ABOGADO', changes:{calm:+10,cred:+5,risk:-10}, flag:'lawyer_speaks', next:4,
      consequence:'Tu abogado argumentará que la detención fue sin orden judicial previa.'},
     {text:'HABLAR TÚ — "¡Ese carro lo pagué trabajando legalmente!"', changes:{calm:-10,cred:-5}, flag:'outburst', next:4,
      consequence:'El juez no necesita escuchar eso ahora. Interrumpiste a tu defensa.'},
   ]},
  {phase:4, location:'Pasillo — Previo a segunda audiencia', bg:'defender', left:'abogado', right:'narco',
   leftName:'LIC. SANDOVAL', leftRole:'Defensor Público Federal',
   speaker:'abogado',
   text:'Escucha: si el informante era policía encubierto y no hubo autorización judicial, hay figura de AGENTE PROVOCADOR. Eso anularía las pruebas. Pero necesito que seas consistente.',
   options:[
     {text:'SEGUIR AL PIE DE LA LETRA — "Lo que usted diga"', changes:{calm:+10,cred:+10,risk:-15}, flag:'follow_lawyer', next:5,
      consequence:'Posible nulidad de pruebas por agente provocador. Esto puede ser determinante.'},
     {text:'DUDAR — "¿Y si eso no funciona?"', changes:{calm:-5,cred:-5}, flag:'doubt_lawyer', next:5,
      consequence:'Tu duda es comprensible pero debilita tu postura en audiencia.'},
     {text:'RECHAZAR — "Yo tengo otro plan"', changes:{cred:-15,risk:+10}, flag:'reject_lawyer', next:5,
      consequence:'Sin estrategia coordinada, el juez notará inconsistencias.'},
   ]},
  {phase:5, location:'Audiencia Final', bg:'judge', left:'juez', right:'narco',
   leftName:'JUEZA DE CONTROL', leftRole:'Poder Judicial',
   speaker:'juez',
   text:'Voy a resolver. El argumento de agente provocador tiene mérito jurídico. Sin embargo, la posesión de la sustancia está documentada. ¿Última palabra?',
   options:[
     {text:'RECONOCER EL ERROR — "Sé que cometí un error"', changes:{cred:+5,risk:-5}, flag:'acknowledge', next:'end'},
     {text:'SOSTENER INOCENCIA — "El procedimiento fue ilegal"', changes:{calm:+5,cred:+5,risk:-10}, flag:'fight', next:'end'},
     {text:'SILENCIO — Solo miras a la jueza', changes:{calm:+5}, flag:'silent_judge', next:'end'},
   ]},
],

loco: [
  {phase:1, location:'Puente — Vía pública', bg:'street_night', left:'cop', right:'loco',
   leftName:'AGENTE ORTIZ', leftRole:'Policía de Proximidad',
   speaker:'cop',
   text:'¡Oye! ¡Para! ¡Dejaste de aventar cosas! ¡Mira el daño que hiciste! ¿Puedes hablar conmigo?',
   options:[
     {text:'HABLAR CONFUSO — Mezclas palabras sin sentido', changes:{calm:+5,pressure:-5,risk:-5}, flag:'incoherent', next:1,
      consequence:'El policía solicita evaluación psiquiátrica. Protocolo de inimputabilidad.'},
     {text:'PONERTE AGRESIVO — Lanzas otra piedra', changes:{calm:-20,pressure:+25,risk:+20}, flag:'violent', next:1,
      consequence:'Se llama fuerza adicional. Ahora hay lesiones a policía en el expediente.'},
     {text:'HUIR — Intentas correr', changes:{calm:-10,pressure:+15,risk:+10}, flag:'flee', next:1,
      consequence:'Te alcanzan. Resistencia a la autoridad se suma a los cargos.'},
     {text:'SENTARTE Y LLORAR — Te desplomas', changes:{calm:+10,pressure:-10,risk:-10}, flag:'breakdown', next:1,
      consequence:'El oficial llama a servicios de salud mental. Primer paso para dictamen pericial.'},
   ]},
  {phase:1, location:'Patrulla — Camino a instalaciones de salud', bg:'patrol_car', left:'cop', right:'loco',
   leftName:'PARAMÉDICO SILVA', leftRole:'Servicios de Emergencia',
   speaker:'cop',
   text:'Vamos a llevarte a que te revise un doctor. ¿Tienes familia? ¿Sabes cómo te llamas?',
   options:[
     {text:'DAR TU NOMBRE', changes:{calm:+5,cred:+5}, flag:'gave_name', next:2,
      consequence:'Genaro. Solo Genaro. No recuerdas apellidos.'},
     {text:'NO RESPONDER — Miras por la ventana', changes:{pressure:-5,risk:-5}, flag:'no_response', next:2,
      consequence:'El paramédico anota: "paciente disociado, posible cuadro psicótico".'},
     {text:'AGITARTE — "¡Me van a matar!"', changes:{calm:-15,pressure:+20}, flag:'panic', next:2,
      consequence:'Te sedan. Llegas esposado a las instalaciones.'},
   ]},
  {phase:2, location:'CAISAME — Centro de Atención', bg:'hospital', left:'fiscal', right:'loco',
   leftName:'DRA. MORA', leftRole:'Perito Psiquiátrico',
   speaker:'fiscal',
   text:'Genaro, necesito hacerte algunas preguntas para entender lo que pasó. ¿Por qué aventaste las piedras?',
   options:[
     {text:'EXPLICAR TU MUNDO — "Los carros me atacan de noche"', changes:{calm:+5,pressure:-5,risk:-15}, flag:'explain_delusion', next:3,
      consequence:'La doctora toma notas. Posible diagnóstico de psicosis. Esto activa el Art. 406 CNPP.'},
     {text:'NO SABER — "No sé, simplemente... los quería alejar"', changes:{calm:+5,risk:-10}, flag:'confused', next:3,
      consequence:'Respuesta consistente con estado disociativo.'},
     {text:'NEGARLO TODO — "Yo no hice nada"', changes:{cred:-10,pressure:+10}, flag:'deny_all', next:3,
      consequence:'La doctora anota inconsistencia. El video contradice tu negación.'},
   ]},
  {phase:3, location:'Audiencia — Sala especial', bg:'court', left:'fiscal', right:'loco',
   leftName:'FISCAL MORALES', leftRole:'Fiscalía',
   speaker:'fiscal',
   text:'El daño en los vehículos asciende a $12,000 pesos. El lesionado tiene fractura en el brazo. Aunque el acusado presenta condición mental, pedimos medidas de seguridad.',
   options:[
     {text:'DEJAR QUE EL ABOGADO ARGUMENTE', changes:{calm:+10,risk:-10}, flag:'lawyer_speaks', next:4,
      consequence:'El defensor invoca la inimputabilidad. Art. 406-412 CNPP.'},
     {text:'HABLAR — "Yo no quería hacerles daño"', changes:{cred:+5,pressure:-5}, flag:'speak', next:4,
      consequence:'El juez escucha con atención. Tu lucidez en este momento es relevante.'},
   ]},
  {phase:4, location:'Sala de espera', bg:'defender', left:'abogado', right:'loco',
   leftName:'LIC. PAREDES', leftRole:'Defensor Público',
   speaker:'abogado',
   text:'Genaro, el dictamen dice que al momento de los hechos no podías comprender que estabas haciendo algo malo. Eso se llama inimputabilidad. No irás a la cárcel, pero pueden mandarte a tratamiento psiquiátrico. ¿Lo entiendes?',
   options:[
     {text:'ENTENDER Y ACEPTAR — "Quiero ayuda"', changes:{calm:+15,risk:-20}, flag:'accept_help', next:5,
      consequence:'Primera vez en mucho tiempo que alguien te ofrece algo. Asientes.'},
     {text:'CONFUNDIRTE — "¿Pero yo hice algo malo?"', changes:{calm:-5,pressure:+5}, flag:'confused2', next:5,
      consequence:'El defensor te explica de nuevo. Es un proceso largo.'},
     {text:'RECHAZAR — "No estoy loco"', changes:{calm:-10,pressure:+10,risk:+10}, flag:'deny_mental', next:5,
      consequence:'Si niegas el diagnóstico, la ruta legal cambia y es menos favorable.'},
   ]},
  {phase:5, location:'Audiencia Final', bg:'judge', left:'juez', right:'loco',
   leftName:'JUEZ DE CONTROL', leftRole:'Poder Judicial',
   speaker:'juez',
   text:'Habiendo revisado el dictamen pericial y conforme al Art. 406 del CNPP, este juzgado resolverá tomando en cuenta el estado de inimputabilidad. Genaro, ¿hay algo que quieras decirle al lesionado?',
   options:[
     {text:'DISCULPARTE — "Lo siento... no sé lo que me pasa"', changes:{cred:+10,risk:-15}, flag:'apologize', next:'end'},
     {text:'NO ENTENDER — Miras al señor lesionado confundido', changes:{calm:+5}, flag:'confused_end', next:'end'},
     {text:'PEDIR AYUDA — "Quiero que me curen"', changes:{calm:+15,risk:-20}, flag:'ask_help', next:'end'},
   ]},
],
};

const PHASE_NAMES = ['','FASE 1: DETENCIÓN','FASE 2: INTERROGATORIO','FASE 3: FISCALÍA','FASE 4: DEFENSOR PÚBLICO','FASE 5: JUEZ'];
const PHASE_SUBS = ['','La policía te detuvo. Cada palabra puede usarse en tu contra.','El Ministerio Público busca inconsistencias en tu historia.','La fiscalía presenta su caso. Ataca como en un RPG.','Tu defensor: aliado... o carga. Tú decides.','El juez escucha todo. No hay marcha atrás.'];
